version: '3'
 
services:
  app:
    image: swirlai/swirl-search:latest
    ports:
      - "8000:8000"
    command: >
      sh -c "rm -fr ./.swirl && python swirl.py setup &&
             python swirl.py start rabbitmq celery-worker celery-beats &&
             daphne -b 0.0.0.0 -p 8000 swirl_server.asgi:application"
             
