version: '3'
 
services:
  app:
    image: joshsgoldstein/swirl-search:1.2
    ports:
      - "8000:8000"
    command: >
      sh -c "python swirl.py setup &&
             python manage.py migrate &&
             python swirl.py stop rabbitmq celery-worker celery-beats &&
             python swirl.py start rabbitmq celery-worker celery-beats &&
             python manage.py runserver 0.0.0.0:8000"