services:
  redis:
    image: redis
  app:
    image: swirlai/swirl-search:latest
    ports:
      - "8000:8000"
    command: >
      sh -c 'rm -fr ./.swirl && python swirl.py setup && mkdir -p static/api/config &&
             /usr/bin/jq ".default" ./config-swirl-demo.db.json | sed -e "s/<msal-app-id>/$MSAL_APP_ID/" \
                 -e "s/<msal-tenant-id>/$MSAL_TENANT_ID/" \
                 -e "s/<msal-port>/$MSAL_CB_PORT/" \
                 -e "s/<msal-host>/$MSAL_HOST/" \
                 -e "s/\"microsoftGalaxyOauth\": false,/\"microsoftGalaxyOauth\": true,/" > static/api/config/default &&
             python swirl.py start celery-worker celery-beats &&
             daphne -b 0.0.0.0 -p 8000 swirl_server.asgi:application'
    environment: # Environment variables section
      - OPENAI_API_KEY=${OPENAI_API_KEY}
