name: Docker Build for amd64

# Build amd64 docker image for SWIRL

on: # build at 05:05 UTC each day
 schedule:
 - cron: '05 05 * * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: login to docker hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build the Docker image
      run: docker build -t swirlai/swirl-search:release_2_5-amd64 .
    - name: Publish the image to DockerHub
      run: docker push swirlai/swirl-search:release_2_5-amd64
