name: Ingegration API Tests

on:
  push:
    branches:
      - 'develop'
  schedule:
  - cron: '05 05 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.11'
            cache: 'pip' # caching pip stuff
    - name: Run Install Swirl
      run: ./install.sh
    - name: Update apt
      run: sudo apt -o Acquire::Retries=3 update
    - name: upgrade Ubuntu to latest patches
      run: sudo apt upgrade -y
    - name: stop update-notifier which restarts datetime
      run: sudo systemctl stop update-notifier-download.timer    
    - name: disable update-notifier which restarts datetime
      run: sudo systemctl disable update-notifier-download.timer
    - name: Run Install redist-server
      run: sudo apt install -y redis-server
    - name: stop system redis
      run: sudo systemctl stop redis-server.service
    - name: Set up SWIRL
      run: python swirl.py setup
    - name: chown swirl redis.conf
      run: sudo chown -R redis.redis /home/runner/work/swirl-search/swirl-search/redis.conf
    - name: Start up SWIRL
      run: python swirl.py start
    - name: Run Integrated API tests
      run: docker run --net=host -t swirlai/swirl-search:latest-integrated-api sh -c "behave --tags=integrated_api"
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
