name: IntegrationAPITests

on:
  workflow_run:
    workflows: [SmokeTests]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_branch }}
    - name: Print full branch reference
      run: |
        echo "Running on reference: ${{ github.ref }}"
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.11'
            cache: 'pip' # caching pip stuff
    - name: Run Install Swirl
      run: ./install.sh
    - name: Update apt
      run: sudo apt -o Acquire::Retries=3 update
    - name: upgrade Ubuntu to latest patches
      run: sudo apt upgrade -y
    - name: stop update-notifier which restarts datetime
      run: sudo systemctl stop update-notifier-download.timer
    - name: disable update-notifier which restarts datetime
      run: sudo systemctl disable update-notifier-download.timer
    - name: Run Install redist-server
      run: sudo apt install -y redis-server
    - name: Set up Swirl
      run: python swirl.py setup
    - name: Start up Swirl
      run: python swirl.py start
    - name: Run Integrated API tests
      run: docker run --net=host -t swirlai/swirl-testing:latest-integrated-api sh -c "behave --tags=integrated_api"
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
