name: SmokeTests

on:
  workflow_run:
    workflows: [UnitTests]
    types:
      - completed
  workflow_dispatch:

jobs:

  build:
    if: (github.event_name == 'workflow_dispatch') || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest

    steps:
    - name: Print Branch Name
      run: echo "Running on reference: $GITHUB_REF"
    - name: Checkout code with specific branch
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
            python-version: '3.11'
            cache: 'pip' # caching pip stuff
    - name: Run Install Swirl
      run: ./install.sh
    - name: Update apt
      run: sudo apt -o Acquire::Retries=3 update
    - name: upgrade Ubuntu to latest patches
      run: sudo apt upgrade -y
    - name: Run Install redis-server
      run: sudo apt install -y redis-server
    - name: Set up Swirl
      run: python swirl.py setup
    - name: Start up Swirl
      run: python swirl.py start
    - name: Run Smoke tests
      run: docker run --net=host -t swirlai/swirl-testing:latest-smoke-test sh -c "behave **/docker_container/*.feature --tags=docker_api_smoke"
    - name: Upload log files
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: log-files
        path: |
          logs/
          /var/log/syslog*
